package catalog

import (
	"fmt"
	"io"
	"strings"

	"github.com/KubedAI/ossie-semantic-operator/api/v1alpha1"
)

// ossieSpecVersion is the Apache Ossie core-spec version the generated
// spec.ossie block conforms to. Matches ossiectl's default osi-version stamp.
const ossieSpecVersion = "0.2.0.dev0"

// TemplateOptions parameterizes the SemanticModel scaffold emitted by
// RenderTemplate. All fields are physical/naming choices; nothing here is a
// business semantic.
type TemplateOptions struct {
	CRName    string // metadata.name
	Namespace string // metadata.namespace
	Catalog   string // spec.connection.catalog (StarRocks external catalog)
	Database  string // spec.connection.database
	Model     string // spec.ossie.name
}

// RenderTemplate writes a SemanticModel YAML scaffold to w. The physical parts
// (connection, datasets, fields) are populated from the catalog tables; the
// business parts (metrics, relationships, governance, views, synonyms) are
// emitted as clearly-marked placeholders for a human to fill in. The output is
// intentionally valid out of the box (empty primary_key/relationships/metrics
// are legal) so `ossiectl validate` passes immediately and the file grows richer
// as placeholders are filled.
//
// The generated file mirrors the shape of a hand-authored SemanticModel so
// business users edit in place rather than learning the schema from scratch.
func RenderTemplate(w io.Writer, opts TemplateOptions, tables []Table) error {
	datasets := DeriveDatasets(tables)
	candidates := InferRelationships(tables)

	// p writes one line, remembering the first write error so the whole render
	// can fail fast to the caller (e.g. a full disk when writing to -out).
	var werr error
	p := func(format string, a ...any) {
		if werr != nil {
			return
		}
		_, werr = fmt.Fprintf(w, format+"\n", a...)
	}

	// --- Provenance / standards note ---
	p("# Generated by `ossiectl derive`. The spec.ossie block is an Apache Ossie")
	p("# semantic_model entry conforming to the Ossie core spec (v%s):", ossieSpecVersion)
	p("#   https://github.com/apache/ossie/blob/main/core-spec/spec.md")
	p("# Physical structure (datasets, fields) is populated from the catalog;")
	p("# business semantics (metrics, relationships, synonyms, governance) are")
	p("# placeholders marked TODO for a human to fill. connection/governance/views")
	p("# are operator extensions kept outside the portable spec.ossie block.")

	// --- Header ---
	p("apiVersion: %s", v1alpha1.GroupVersion.String())
	p("kind: SemanticModel")
	p("metadata:")
	p("  name: %s", opts.CRName)
	p("  namespace: %s", opts.Namespace)
	p("spec:")
	p("  connection:")
	p("    catalog: %s        # StarRocks external catalog fronting the lake", opts.Catalog)
	p("    database: %s", opts.Database)
	p("    viewDatabase: semantic_views   # where governed BI views are created")

	// --- Ossie model ---
	p("  ossie:")
	p("    name: %s", opts.Model)
	p(`    description: ""                 # TODO: one line describing this model`)
	p("    # ai_context guides LLM agents. Fill in and uncomment.")
	p("    # ai_context:")
	p("    #   instructions: >-")
	p("    #     TODO: what this model is for; call out any metric whose definition")
	p("    #     differs from naive per-row math (e.g. fan-out-safe ratios).")

	// --- Datasets (auto-populated from the catalog) ---
	p("    datasets:")
	for _, d := range datasets {
		p("      - name: %s", yamlScalar(d.Name))
		p("        source: %s", yamlScalar(d.Name))
		p("        primary_key: []              # TODO: set PK column(s), e.g. [%s]; required for fan-out-safe ratio metrics", exampleKey(d))
		p("        # unique_keys:               # TODO: optional; other unique keys, each [col] or [col1, col2]")
		p(`        # description: ""            # TODO: describe this dataset`)
		p("        # ai_context:")
		p(`        #   synonyms: []             # TODO: business names, e.g. ["sales", "transactions"]`)
		if len(d.Fields) == 0 {
			p("        fields: []                   # (no columns found for this table in the catalog)")
			continue
		}
		p("        fields:")
		for i := range d.Fields {
			f := &d.Fields[i]
			body, ok := f.Expression.Select()
			if !ok || body == "" {
				body = f.Name // identity fallback; DeriveDatasets always sets this
			}
			p("          - name: %s", yamlScalar(f.Name))
			p("            expression:")
			p("              dialects:")
			p("                - dialect: ANSI_SQL")
			p("                  expression: %s", yamlScalar(body))
			if f.Dimension != nil && f.Dimension.IsTime {
				p("            dimension:")
				p("              is_time: true")
			}
			if f.Description != "" {
				p("            description: %s", yamlQuote(f.Description))
			}
		}
	}

	// --- Relationships (inferred, commented for review) ---
	p("")
	p("    # relationships: Glue/Iceberg do not record foreign keys. The edges below")
	p("    # were inferred from *_sk / *_id naming. Review each and move the correct")
	p("    # ones into the list (delete the leading '#').")
	p("    relationships: []")
	for i := range candidates {
		c := &candidates[i]
		p("    #  - name: %s", c.Name)
		p("    #    from: %s", c.From)
		p("    #    to: %s", c.To)
		p("    #    from_columns: [%s]", strings.Join(c.FromColumns, ", "))
		p("    #    to_columns: [%s]", strings.Join(c.ToColumns, ", "))
		p("    #    # %s", c.Reason)
	}

	// --- Metrics (business definitions; example provided) ---
	p("")
	p("    # metrics: certified aggregate definitions, the core of the model. A model")
	p("    # with no metrics validates but answers nothing; define at least one. Example:")
	p("    metrics: []")
	p("    #  - name: total_sales")
	p("    #    expression:")
	p("    #      dialects:")
	p("    #        - dialect: ANSI_SQL")
	p("    #          expression: SUM(store_sales.ss_ext_sales_price)")
	p("    #    description: Total sales revenue")
	p("    #    ai_context:")
	p(`    #      synonyms: ["revenue", "total sales", "gross sales"]`)

	// --- Governance (top-level under spec; commented example) ---
	p("")
	p("  # governance: compile-time row/column access policy. Uncomment and edit.")
	p("  # governance:")
	p("  #   defaultRole: analyst")
	p("  #   roles:")
	p("  #     - name: analyst")
	p(`  #       allowMetrics: ["*"]`)
	p(`  #       denyFields: []                 # e.g. ["customer.c_email_address"]`)

	// --- Views (top-level under spec; commented example) ---
	p("")
	p("  # views: governed BI views materialized in StarRocks. Uncomment and edit.")
	p("  # views:")
	p("  #   - name: sales_by_category")
	p("  #     metrics: [total_sales]")
	p("  #     dimensions: [item.i_category]")
	p("  #     role: analyst")

	// --- Joins (top-level under spec; per-relationship join type override) ---
	p("")
	p("  # joins: per-relationship join type override (INNER default). Uncomment and edit.")
	p("  # joins:")
	p("  #   - relationship: <relationship_name>")
	p("  #     type: LEFT")

	return werr
}

// yamlScalar renders s as a bare YAML token when it is a safe identifier, or a
// double-quoted scalar otherwise. Physical identifiers from a catalog are
// almost always bare (keeping output readable), but arbitrary catalogs may
// carry names with spaces or punctuation that must be quoted to stay valid.
func yamlScalar(s string) string {
	if isBareToken(s) {
		return s
	}
	return yamlQuote(s)
}

// isBareToken reports whether s is a plain [A-Za-z0-9_] identifier that needs
// no YAML quoting.
func isBareToken(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !(c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9') {
			return false
		}
	}
	return true
}

// exampleKey returns a plausible primary-key column name for the placeholder
// hint: the first field that looks like a surrogate/business key, else the
// first field, else a generic "id".
func exampleKey(d v1alpha1.Dataset) string {
	for i := range d.Fields {
		n := d.Fields[i].Name
		if strings.HasSuffix(n, "_sk") || strings.HasSuffix(n, "_id") {
			return n
		}
	}
	if len(d.Fields) > 0 {
		return d.Fields[0].Name
	}
	return "id"
}

// yamlQuote renders s as a double-quoted YAML scalar, escaping backslashes and
// double quotes, so comments/descriptions with special characters stay valid.
func yamlQuote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", " ")
	return `"` + r.Replace(s) + `"`
}
