//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIContext) DeepCopyInto(out *AIContext) {
	*out = *in
	if in.Synonyms != nil {
		in, out := &in.Synonyms, &out.Synonyms
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Examples != nil {
		in, out := &in.Examples, &out.Examples
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIContext.
func (in *AIContext) DeepCopy() *AIContext {
	if in == nil {
		return nil
	}
	out := new(AIContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionSpec) DeepCopyInto(out *ConnectionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionSpec.
func (in *ConnectionSpec) DeepCopy() *ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomExtension) DeepCopyInto(out *CustomExtension) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomExtension.
func (in *CustomExtension) DeepCopy() *CustomExtension {
	if in == nil {
		return nil
	}
	out := new(CustomExtension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dataset) DeepCopyInto(out *Dataset) {
	*out = *in
	if in.PrimaryKey != nil {
		in, out := &in.PrimaryKey, &out.PrimaryKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UniqueKeys != nil {
		in, out := &in.UniqueKeys, &out.UniqueKeys
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.AIContext != nil {
		in, out := &in.AIContext, &out.AIContext
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]Field, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomExtensions != nil {
		in, out := &in.CustomExtensions, &out.CustomExtensions
		*out = make([]CustomExtension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dataset.
func (in *Dataset) DeepCopy() *Dataset {
	if in == nil {
		return nil
	}
	out := new(Dataset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetBinding) DeepCopyInto(out *DatasetBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetBinding.
func (in *DatasetBinding) DeepCopy() *DatasetBinding {
	if in == nil {
		return nil
	}
	out := new(DatasetBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DialectExpression) DeepCopyInto(out *DialectExpression) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DialectExpression.
func (in *DialectExpression) DeepCopy() *DialectExpression {
	if in == nil {
		return nil
	}
	out := new(DialectExpression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dimension) DeepCopyInto(out *Dimension) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dimension.
func (in *Dimension) DeepCopy() *Dimension {
	if in == nil {
		return nil
	}
	out := new(Dimension)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Expression) DeepCopyInto(out *Expression) {
	*out = *in
	if in.Dialects != nil {
		in, out := &in.Dialects, &out.Dialects
		*out = make([]DialectExpression, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Expression.
func (in *Expression) DeepCopy() *Expression {
	if in == nil {
		return nil
	}
	out := new(Expression)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalAuthorizationSpec) DeepCopyInto(out *ExternalAuthorizationSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalAuthorizationSpec.
func (in *ExternalAuthorizationSpec) DeepCopy() *ExternalAuthorizationSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalAuthorizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Field) DeepCopyInto(out *Field) {
	*out = *in
	in.Expression.DeepCopyInto(&out.Expression)
	if in.Dimension != nil {
		in, out := &in.Dimension, &out.Dimension
		*out = new(Dimension)
		**out = **in
	}
	if in.AIContext != nil {
		in, out := &in.AIContext, &out.AIContext
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomExtensions != nil {
		in, out := &in.CustomExtensions, &out.CustomExtensions
		*out = make([]CustomExtension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Field.
func (in *Field) DeepCopy() *Field {
	if in == nil {
		return nil
	}
	out := new(Field)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernanceSpec) DeepCopyInto(out *GovernanceSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]RolePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalAuthorizationSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernanceSpec.
func (in *GovernanceSpec) DeepCopy() *GovernanceSpec {
	if in == nil {
		return nil
	}
	out := new(GovernanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
	in.Expression.DeepCopyInto(&out.Expression)
	if in.AIContext != nil {
		in, out := &in.AIContext, &out.AIContext
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomExtensions != nil {
		in, out := &in.CustomExtensions, &out.CustomExtensions
		*out = make([]CustomExtension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OssieModel) DeepCopyInto(out *OssieModel) {
	*out = *in
	if in.AIContext != nil {
		in, out := &in.AIContext, &out.AIContext
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Datasets != nil {
		in, out := &in.Datasets, &out.Datasets
		*out = make([]Dataset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Relationships != nil {
		in, out := &in.Relationships, &out.Relationships
		*out = make([]Relationship, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomExtensions != nil {
		in, out := &in.CustomExtensions, &out.CustomExtensions
		*out = make([]CustomExtension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OssieModel.
func (in *OssieModel) DeepCopy() *OssieModel {
	if in == nil {
		return nil
	}
	out := new(OssieModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Relationship) DeepCopyInto(out *Relationship) {
	*out = *in
	if in.FromColumns != nil {
		in, out := &in.FromColumns, &out.FromColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ToColumns != nil {
		in, out := &in.ToColumns, &out.ToColumns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AIContext != nil {
		in, out := &in.AIContext, &out.AIContext
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomExtensions != nil {
		in, out := &in.CustomExtensions, &out.CustomExtensions
		*out = make([]CustomExtension, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Relationship.
func (in *Relationship) DeepCopy() *Relationship {
	if in == nil {
		return nil
	}
	out := new(Relationship)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelationshipJoin) DeepCopyInto(out *RelationshipJoin) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelationshipJoin.
func (in *RelationshipJoin) DeepCopy() *RelationshipJoin {
	if in == nil {
		return nil
	}
	out := new(RelationshipJoin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolePolicy) DeepCopyInto(out *RolePolicy) {
	*out = *in
	if in.AllowMetrics != nil {
		in, out := &in.AllowMetrics, &out.AllowMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyFields != nil {
		in, out := &in.DenyFields, &out.DenyFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RowFilters != nil {
		in, out := &in.RowFilters, &out.RowFilters
		*out = make([]RowFilter, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolePolicy.
func (in *RolePolicy) DeepCopy() *RolePolicy {
	if in == nil {
		return nil
	}
	out := new(RolePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RowFilter) DeepCopyInto(out *RowFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RowFilter.
func (in *RowFilter) DeepCopy() *RowFilter {
	if in == nil {
		return nil
	}
	out := new(RowFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticModel) DeepCopyInto(out *SemanticModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticModel.
func (in *SemanticModel) DeepCopy() *SemanticModel {
	if in == nil {
		return nil
	}
	out := new(SemanticModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SemanticModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticModelList) DeepCopyInto(out *SemanticModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SemanticModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticModelList.
func (in *SemanticModelList) DeepCopy() *SemanticModelList {
	if in == nil {
		return nil
	}
	out := new(SemanticModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SemanticModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticModelSpec) DeepCopyInto(out *SemanticModelSpec) {
	*out = *in
	out.Connection = in.Connection
	in.Ossie.DeepCopyInto(&out.Ossie)
	if in.Governance != nil {
		in, out := &in.Governance, &out.Governance
		*out = new(GovernanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Views != nil {
		in, out := &in.Views, &out.Views
		*out = make([]ViewSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Joins != nil {
		in, out := &in.Joins, &out.Joins
		*out = make([]RelationshipJoin, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticModelSpec.
func (in *SemanticModelSpec) DeepCopy() *SemanticModelSpec {
	if in == nil {
		return nil
	}
	out := new(SemanticModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SemanticModelStatus) DeepCopyInto(out *SemanticModelStatus) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]DatasetBinding, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SemanticModelStatus.
func (in *SemanticModelStatus) DeepCopy() *SemanticModelStatus {
	if in == nil {
		return nil
	}
	out := new(SemanticModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewFilter) DeepCopyInto(out *ViewFilter) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewFilter.
func (in *ViewFilter) DeepCopy() *ViewFilter {
	if in == nil {
		return nil
	}
	out := new(ViewFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ViewSpec) DeepCopyInto(out *ViewSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dimensions != nil {
		in, out := &in.Dimensions, &out.Dimensions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]ViewFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ViewSpec.
func (in *ViewSpec) DeepCopy() *ViewSpec {
	if in == nil {
		return nil
	}
	out := new(ViewSpec)
	in.DeepCopyInto(out)
	return out
}
